// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKi4yeRcibSuOZDb86lzpbO3q6bZzynAw',
    appId: '1:214366574091:web:2a453b5aae7e28364b990e',
    messagingSenderId: '214366574091',
    projectId: 'alibabaapp-2d18c',
    authDomain: 'alibabaapp-2d18c.firebaseapp.com',
    storageBucket: 'alibabaapp-2d18c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLQOe1pvS2buaI-4VtbFVaobQlQ4sASJE',
    appId: '1:214366574091:android:f78c5cdfb05521f34b990e',
    messagingSenderId: '214366574091',
    projectId: 'alibabaapp-2d18c',
    storageBucket: 'alibabaapp-2d18c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDojSgBjn6pIyi4MVvNYXyhoXk3yMc_MdA',
    appId: '1:214366574091:ios:bc7fdbb87fd1ebf64b990e',
    messagingSenderId: '214366574091',
    projectId: 'alibabaapp-2d18c',
    storageBucket: 'alibabaapp-2d18c.appspot.com',
    iosBundleId: 'com.example.alibabaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDojSgBjn6pIyi4MVvNYXyhoXk3yMc_MdA',
    appId: '1:214366574091:ios:143002fbab237edf4b990e',
    messagingSenderId: '214366574091',
    projectId: 'alibabaapp-2d18c',
    storageBucket: 'alibabaapp-2d18c.appspot.com',
    iosBundleId: 'com.example.alibabaApp.RunnerTests',
  );
}
